dataset_params:
  dataset: 'imagenet'
  image_size: 224
  batch_size: 1024
  patch_size: 16
  pred_ratio: 0.3
  min_aspect_ratio: 0.3
  num_workers: 16
  prefetch_factor: 4
  data_path: /dev/shm/imagenet/train
  val_data_path: /dev/shm/imagenet/val
  global_crops_scale: [0.4, 1.]
  local_crops_scale: [0.05, 0.4]
  num_global_crops: 2
  num_local_crops: 8

dino:
  seed: 61
  arch: vit_small
  epochs: 100
  linear_epochs: 500
  student_temp: 0.1
  teacher_temp: 0.04
  warmup_teacher_temp: 0.04
  warmup_teacher_temp_epochs: 0
  koleo_loss_weight: 0.1
  checkpoint_path: /home/muhammetcan/checkpoints/dino_vit_small_16.pkl
  linear_eval_checkpoint_path: /home/muhammetcan/checkpoints/dino_vit_small_16_lineareval.pkl
  num_classes: 1000
  student_params:
    patch_size: 16
    drop_path_rate: 0.1
    mask_im_modeling: True
  teacher_params:
    patch_size: 16
  proj_params:
    hidden_dim: 2048
    bottleneck_dim: 256
    n_layers: 3
  head_params:
    hidden_dim: 8192
  optim_params:
    lr: 0.0005
    min_lr: 1e-6
    warmup_epochs: 10
    weight_decay: 0.04
    weight_decay_end: 0.4
    grad_clip: 3.0
    momentum_teacher: 0.996

wandb:
  project: 'DINO'
  name: 'Dino imagenet'